version: '3.4'

services:
  neighborgood.api:
    image: ${DOCKER_REGISTRY-}neighborgoodapi
    build:
      context: .
      dockerfile: NeighborGood.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"

 neighborgood.DataBase:
    container_name: DataBase
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: Password2020
    ports:
        -"1450:1433"